targets:
  nigiri:
    source: https://github.com/oota-sushikuitee/nigiri
    default-branch: main
    build-command:
      linux: make build
      windows: make build
      darwin: make build
  dotfiles:
    source: https://github.com/Okabe-Junya/dotfiles
    default-branch: main
    build-command:
      linux: make
      windows: make
      darwin: make
  configs:
    source: https://github.com/Okabe-Junya/.github
    default-branch: main
    build-command:
      linux: make
      windows: make
      darwin: make
defaults:
  build-command:
    linux: make build
    windows: make build
    darwin: make build
