version: "2"
run:
  go: "1.23"
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - noctx
    - staticcheck
    - unused
  settings:
    govet:
      disable:
        - shadow
      enable-all: true
    staticcheck:
      checks:
        - -SA1006
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - govet
          - noctx
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
